spring:
  application:
    name: Gateway
  config:
    import: "optional:consul:http://consul:8500"
  cloud:
    gateway:
      routes:
        # ProfileManager service
        - id: profiles
          uri: lb://ProfileManager
          predicates:
            - Path=/profiles,/profiles/**
        # MatchingService
        - id: match
          uri: lb://MatchingService
          predicates:
            - Path=/match,/match/**
        # MatchRetrivalService
        - id: retrieval
          uri: lb://MatchRetrivalService
          predicates:
            - Path=/matches,/matches/**
        # MessageService
        - id: messages
          uri: lb://MessageService
          predicates:
            - Path=/messages,/messages/**
        # AuthenticationService
        - id: auth
          uri: lb://AuthentificationService
          predicates:
            - Path=/auth,/auth/**

    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    rabbit:
      enabled: true
    db:
      enabled: true
